services:
  app:
    build: .
    init: true
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_TOKEN=${TWILIO_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
      - REDIS_HOST=redis
      - WEBHOOK_URL=${WEBHOOK_URL}
      - TZ=Europe/Stockholm

  redis:
    image: redis:alpine
    restart: always
